### ISSUE TITLE
Collected API improvements

### ISSUE THREAD

**Issue by jonpryor** [grendello/LibZipSharp#4]
Collected API improvements while reviewing https://github.com/xamarin/xamarin-android/pull/89

Namespace should be `Xamarin.Zip` or `Xamarin.Tools.Zip`, not `Xamarin.ZipSharp`. A `Sharp` suffix adds nothing.

`ZipArchive.NumberOfEntries` should be named `ZipArchive.EntryCount`. Alternatively, *maybe* follow `System.IO.Collections` and have an `Entries` property of `ICollection<ZipEntry>` with a `Count` property.

`ZipEntry.Name` should be `ZipEntry.FullName`, a'la System.IO.Collections, if (I assume!) the value is the "full" name of an entry within the .zip file, e.g. `foo/bar/baz.txt` instead of just `baz.txt`.

`ZipArchive.AddFile(string, CompressionMethod)` should name the `CompressionMethod` parameter `compressionMethod`, not just `method`.

**Comment by grendello** [comment]
* changed the namespace to `Xamarin.Tools.Zip`
 * renamed `ZipArchive.NumberOfEntries` to `EntryCount`. Using a collection of entries is wasteful (time and memory wise) as `EntryCount` simply calls a function in the native library that returns the number of entries read from the ZIP directory instead of iterating over all entries
 * renamed `ZipEntry.Name` to `ZipEntry.FullName`
 * renamed all the `CompressionMethod method` parameters to `compressionMethod`
